### ISSUE TITLE
PT-PT keyboard layout addition request

### ISSUE THREAD

**Issue by brunoais** [anssih/finqwerty#12]
Can you make a keyboard layout like this one:
![f(x)tec_pro1_lat-layout__balanced_compromise_ç](https://user-images.githubusercontent.com/639467/74058483-0f828200-49de-11ea-904b-adf52e4cac5d.png)
You can view or ask suggested changes [using this](http://www.keyboard-layout-editor.com/##@_css=.keylabel2%20%7B%20color%2F:%20%23FFFF00%20!important%2F%3B%20%7D%3B&@_c=%23555555&t=%23FFFFFF&w:1.5&h:0.65%3B&=%0AEsc%0A%7C%0A%0A%0A%0A%0A%0A%5C&_w:1.25&h:0.65%3B&=%0A1%0A%C2%A1%0A%0A%0A%0A%0A%0A!&_w:1.25&h:0.65%3B&=%0A2%0A%2F@%0A%0A%0A%0A%0A%0A%22&_w:1.25&h:0.65%3B&=%0A3%0A%C2%A7%0A%0A%0A%0A%0A%0A%23&_w:1.25&h:0.65%3B&=%0A4%0A%C2%A3%0A%0A%0A%0A%0A%0A$&_w:1.25&h:0.65%3B&=%0A5%0A%E2%82%B5%0A%0A%0A%0A%0A%0A%25&_w:1.25&h:0.65%3B&=%0A6%0A%C2%AC%0A%0A%0A%0A%0A%0A%2F&&_w:1.25&h:0.65%3B&=%0A7%0A%7B%0A%0A%0A%0A%0A%0A%2F%2F&_w:1.25&h:0.65%3B&=%0A8%0A%5B%0A%0A%0A%0A%0A%0A(&_w:1.25&h:0.65%3B&=%0A9%0A%5D%0A%0A%0A%0A%0A%0A)&_w:1.25&h:0.65%3B&=%0A0%0A%7D%0A%0A%0A%0A%0A%0A%2F=&_w:1.25&h:0.65%3B&=%0A%3F%0A'%0A%0A%0A%0A%0A%0A%C2%BF&_w:1.25&h:0.65%3B&=%60%0A%C2%B4%0A%CB%9D&_w:1.25&h:0.65%3B&=%0A%0A%0ADel%3B&@_y:-0.35&w:1.5&h:0.75%3B&=%0ATab&_w:1.25&h:0.75%3B&=%0AQ%0A%5C&_w:1.25&h:0.75%3B&=%0AW&_w:1.25&h:0.75%3B&=%0AE%0A%E2%82%AC&_w:1.25&h:0.75%3B&=%0AR&_w:1.25&h:0.75%3B&=%0AT&_w:1.25&h:0.75%3B&=%0AY%0A%C2%A5&_w:1.25&h:0.75%3B&=%0AU&_w:1.25&h:0.75%3B&=%0AI&_w:1.25&h:0.75%3B&=%0AO%0A%C5%93&_w:1.25&h:0.75%3B&=%0AP%0A%2F%2F&_w:1.25&h:0.75%3B&=%C2%AA%0A%C2%BA%0A%CB%98&_w:1.25&h:0.75%3B&=*%0A+%0A%C2%B0&_a:6&w:1.25&h:0.75%3B&=%0A%0A%E2%8C%AB%3B&@_y:-0.25&a:4&w:2&h:0.75%3B&=%0ACaps&_w:1.25&h:0.75%3B&=%0AA%0A%C3%A6&_w:1.25&h:0.75%3B&=%0AS&_w:1.25&h:0.75%3B&=%0AD&_w:1.25&h:0.75&n:true%3B&=%0AF%0A%C4%91&_w:1.25&h:0.75%3B&=%0AG&_w:1.25&h:0.75%3B&=%0AH&_w:1.25&h:0.75&n:true%3B&=%0AJ%0A%CC%89&_w:1.25&h:0.75%3B&=%0AK&_w:1.25&h:0.75%3B&=%0AL&_w:1.25&h:0.75%3B&=%0A%C3%87%0A%C3%91&_w:1.25&h:0.75%3B&=%0A~%0A%CB%87%0A%0A%0A%0A%0A%0A%0A%5E&_w:2&h:0.75%3B&=%0A%0A%0A%E2%86%A9%3B&@_y:-0.25&w:1.5&h:0.75%3B&=%0AShift&_w:1.25&h:0.75%3B&=%3C%0A%3E%0A%7C&_w:1.25&h:0.75%3B&=%0AZ&_w:1.25&h:0.75%3B&=%0AX&_w:1.25&h:0.75%3B&=%0AC%0A%C3%87&_w:1.25&h:0.75%3B&=%0AV&_w:1.25&h:0.75%3B&=%0AB&_w:1.25&h:0.75%3B&=%0AN%0A%C3%91&_w:1.25&h:0.75%3B&=%0AM%0A%C2%B5&_w:1.25&h:0.75%3B&=%2F%3B%0A,%0A'&_w:1.25&h:0.75%3B&=%2F:%0A.%0A%C2%A8&_w:1.25&h:0.75%3B&=%2F_%0A-%0A-&_a:7&w:1.25&h:0.75%3B&=%E2%96%B2&_a:4&w:1.25&h:0.75%3B&=%0A%0A%0AShift%3B&@_y:-0.25&w:1.5&h:0.75%3B&=%0ACtrl&_t=%23FFFF00&w:1.25&h:0.75%3B&=%0A%0A%E2%86%97&_a:6&w:1.25&h:0.75%3B&=%C6%92&_t=%23FFFFFF&a:5&w:1.25&h:0.75%3B&=%0AAlt&_a:4&w:1.25&h:0.75%3B&=%0A%0A%E2%98%BA%0A%0A%0A%0A%0A%0A%0A%0ASYM&_t=%23FFFF00&w:5&h:0.75%3B&=%0A%0A%F0%9F%8C%90&_t=%23FFFFFF&a:5&w:1.25&h:0.75%3B&=%0ACtrl&_a:4&w:1.25&h:0.75%3B&=%0A%0A%E2%86%97&_a:7&w:1.25&h:0.75%3B&=%E2%97%80&_w:1.25&h:0.75%3B&=%E2%96%BC&_w:1.25&h:0.75%3B&=%E2%96%B6). If that link doesn't work, here's a json file with the equivalent content:
[f(x)tec_pro1_lat-layout__balanced_compromise_ç.txt](https://github.com/anssih/finqwerty/files/4172563/f.x.tec_pro1_lat-layout__balanced_compromise_c.txt)

This layout is intended for a German QUERTZ physical keyboard acting as a PT-PT (also compatible with PT-BR) physical keyboard for f(x)tec pro¹.
May you do that?

**Comment by anssih** [comment]
Yes, I can add this one. I'll link a test version onto this issue sometime this week.

Thanks :)

**Comment by brunoais** [comment]
Do note I can't test it yet. I still don't know when I will get the phone... It will just be great if I can get this already worked on when I get the phone.
Given that, I have time.

**Comment by anssih** [comment]
OK, no problem, I can do a quick check myself and we can fix it later if needed.

**Comment by brunoais** [comment]
Looks good, @anssih (and fast!). Thank you!

**Comment by anssih** [comment]
Released in v1.6.0.
