### ISSUE TITLE
Waiting Keys " and ' Pro1 US-Int

### ISSUE THREAD

**Issue by beatgutzwiller** [anssih/finqwerty#2]
First of all thank you very much. Appreciate your work and already did use the donation button ;-) (Not so much that I expect special treatment though)

My only problem left is not really a technical problem but a usability problem. 
If i want to insert " into a text I have to type it twice. This is because the OS is waiting for a second character and will make Umlauts out of it if possible ("a => ä, etc...).
This is what windoof does and some people like but it is absolutely unnecessary and slow on a proper US-Int keyboard as you did. AltGr+q is already ä and having a waiting input on " is horrible.

Could this be fixed/made configurable?

**Comment by anssih** [comment]
Yeah, I think we can change the mapping to be more reasonable if needed. Currently, per the [charts](https://android.onse.fi/finqwerty/#pro1), the apostrophe key on the right side of L on FinQwerty US intl for QWERTY is set to:

  key: ´ (combining acute accent)
  shift+key: ¨ (combining diaeresis)
  fn+key: ' (apostrophe)
  fn+shift+key: " (quotation mark)
  fn+ctrl+key: " (quotation mark)
  alt+key: " (quotation mark)

Note that pressing ¨ twice won't get you " (quotes) but plain dots ¨.

Do you think we should swap these around to:

  key: ' (apostrophe)
  shift+key: " (quotation mark)
  fn+key: ´ (combining acute accent)
  fn+shift+key: ¨ (combining diaeresis)
  fn+ctrl+key: ¨ (combining diaeresis)
  alt+key: " (quotation mark)

Or do you have some other idea on a better mapping?

Thanks for the donation :)

**Comment by beatgutzwiller** [comment]
That proposed change would be perfect for me. I think it would make more sense for everyone since the layout does already handle umlauts well.
However there are people used to the combing key behaviour. So the change may get other people complaining. I still propose to go ahead since it is more efficient.

P.S. Sorry for getting it wrong I thought the quotation mark looks strange :)

**Comment by anssih** [comment]
I think we should make the change for now and then reconsider if other people complain.

Here is a test version if you wish to try it out:
https://android.onse.fi/finqwerty/finqwerty-pro1-test32.apk
Layout charts: https://android.onse.fi/finqwerty/pro1-test32.html

I plan to release the next official version next week.

**Comment by beatgutzwiller** [comment]
Works as a charm.
Thank you very much!

**Comment by anssih** [comment]
Change released in v1.5.2.

Thanks :)

**Comment by beatgutzwiller** [comment]
Hi Anssi

Just a minor detail I found:
`: ` (combining backtick)
fn + `: ` (normal backtick)

To stay inline with the change, this should also be switched.

**Comment by pierre-muth** [comment]
Hi there,
If I can humbly add my opinion from my daily usage of US-int on computers.
I'm using a lot dead keys to type French. There is no combo for à (not á) and è (not é).
On computers, US-int has the keys [`], ['] and ["] by default on the combining mode. I agree it should be coherent for all keys. Is it possible to have a layout US-int without and another with these key as base combining ?
Thanks a lot for your work !

**Comment by beatgutzwiller** [comment]
> Hi there,
> If I can humbly add my opinion from my daily usage of US-int on computers.
> I'm using a lot dead keys to type French. There is no combo for à (not á) and è (not é).
> On computers, US-int has the keys [`], ['] and ["] by default on the combining mode. I agree it should be coherent for all keys. Is it possible to have a layout US-int without and another with these key as base combining ?
> Thanks a lot for your work !

Have a look here. On a US-Int (altgr-variant) it is possible to insert è as I do now.
For that you have to press Alt-Gr+` followed by a "e" the same goes for À.

https://dry.sailingissues.com/us-international-keyboard-layout.html

However I understand that it may be cumbersome if it has to be done often. Does French use them a lot? If yes I support your wish for two variants of US-Int. If they are not used that often it may even save you time, since "éáú" etc. are faster to type.

**Comment by pierre-muth** [comment]
Hi 
Yes unfortunately. "à" means "to" or "by". 
For example "Where do you go ? I'm going to the river" is "Où va-tu? Je vais à la rivière". 
These accents are used quite often. The convenient part of the "all dead-key" variant of the US-int is that all letters are done the same way. For example the Ç is ['] then [C], or the ö is ["] then [o]. Personally, I feel I'm thinking less that way, compare to memorize the combinations. But it is a one man opinion, as you said, it is possible with us-int alt-Gr. If a new layout is possible, it would be the cherry on top of the cake ;)

**Comment by enigma9o7** [comment]
On my PC (ubuntu), us-intl is offered both ways.  One with dead keys on first two levels (normal and shift) and with them only on third/4th levels (altgr and altgr+shift).   As an english typer, I dont want any dead keys without altgr, so use the us-intl-altgr layout.  But I can see how a french typer would prefer dead keys on first two levels, which is the standard us-intl layout.

**Comment by anssih** [comment]
Sorry for the delay in response.

I agree that two variants is the way to go, I'll try to get back to this within the next week.

**Comment by pierre-muth** [comment]
> > Sorry for the delay in response.
> > I agree that two variants is the way to go, I'll try to get back to this within the next week.
> 
> Hey Anssih. You are doing that for free... take your time, whenever you are ready!
> I mean I really appreciate it, but there are more important things.
> After all it is open source we could just do it ourselves if our lives are dependent on it.

I totally agree with beatgutzwiller! I first thank you a lot, and don't worry, it is not a delayed answer (plus I'm waiting the phone to arrive). The last thing I want is put pressure on you.

**Comment by anssih** [comment]
Test version with separate U.S. intl variants:

https://android.onse.fi/finqwerty/finqwerty-pro1-test35.apk
https://android.onse.fi/finqwerty/pro1-test35.html

This will be in soon-to-be-released v1.5.3 unless problems are found.

**Comment by anssih** [comment]
There was a problem with missing U.S. Intl with Fn dead keys QWERTZ variant, fixed in test36:
https://android.onse.fi/finqwerty/finqwerty-pro1-test36.apk
https://android.onse.fi/finqwerty/pro1-test36.html

**Comment by beatgutzwiller** [comment]
Dear @anssih
 
As always thank you very much for your work. 
It works as indented. However I am fairly certain that you mixed up the naming.
The one without the deadkeys is named as deadkey layout.

**Comment by pierre-muth** [comment]
Thanks a lot @anssih !
If everything goes as planned, I should be able to test it next week.
Have a nice day!

**Comment by anssih** [comment]
> It works as indented. However I am fairly certain that you mixed up the naming.
> The one without the deadkeys is named as deadkey layout.

I used "U.S. intl." for standard layout and "U.S. intl. with Fn dead keys" for layout with dead keys moved to behind Fn (similar to how the swapped layout is called in Linux: "with AltGr dead keys").

Should I add "with direct dead keys" to the standard U.S. intl layout to make it clearer that both have the dead keys on grave/apostrophe keys, one directly and one behind Fn? Or any other suggestions?

**Comment by beatgutzwiller** [comment]
Well I know them as:
- altgr-intl
- deadkey

DeadKeys are per definition ([wikipedia](https://en.wikipedia.org/wiki/Dead_key)) what the layout you called "with Fn dead keys" does not have at all. That is why it may be a bit confusing.

I did a quick google and found to definition of my layout. As said `US-Int_AltGr` which may not be spot on since there is no `AltGr` on the Pro1. The other I found is:
- US-Int_WithDeadKeys
- US-Int_WithoutDeadKeys

This would be more adapted to the pro1 but less consistent to the rest of the Linux world. 
Just looked up the X11 definitions:

`localectl list-x11-keymap-variants | grep intl`

There it is defined as:
- intl
- altr-intl

I would prefer those to be consistent but are happy as long as it is not named after dead keys :+1:

**Comment by pierre-muth** [comment]
Got a nice surprise, I yet have the phone! I installed the apk from your last link (finqwerty-pro1-test36.apk), and it works great !
I'm using "U.S. intl." (dead key by default), I can see some small differences with the computer version. Mostly the resulting char of the combination with the [" '] key. But I'm not sure if it is due to the system or your mapping.
I'm used to get an apostrophe ( ' ) if I combine this key with a space, and not the accent alone ( ´ ). Same with the shifted key plus space, I'm used to get a the quotation marks ( " ) and not a umlaut alone ( ¨ ). As well, with this key plus the [ c ], I'm used to get a ( ç ) and not a ( ć ). To get the ç, it is [atl]+[c] which is rather hard (have small fingers ;) ).
Do you think it is something you should tune ? I mean, I can use it now even if it is slightly different from a computer. And if I can help by completing a table or something, don't hesitate. 
Anyway, thanks a lot, yet your layout is saving me a lot of learning time on the pro1 keyboard!

**Comment by anssih** [comment]
> Just looked up the X11 definitions:
> 
> `localectl list-x11-keymap-variants | grep intl`
> 
> There it is defined as:
> 
> * intl
> * altr-intl

That commands only prints the identifiers, the descriptions for those layouts (that desktop UIs show) are:

- intl: "English (US, intl., with dead keys)"
- altgr-intl: "English (intl., with AltGr dead keys)"

So both do have the "dead keys" in the name. And I'd rather not describe the second variant as "without dead keys" if the PC Linux altgr-intl variant is described as *having* dead keys.

I've now added "with dead keys" to the "main" US intl layout to make it slightly less confusing:

- FinQwerty F(x)tec Pro1, U.S. intl. with dead keys for physical US QWERTY
- FinQwerty F(x)tec Pro1, U.S. intl. with Fn dead keys for physical US QWERTY

Do you think it is OK now, or do you have suggestions? :)

@pierre-muth I'll get to your comment later, within the next 2 days.

**Comment by beatgutzwiller** [comment]
@anssih 
What the heck....??! I mean I totally believe you (Do not really have that kind of guy, mine says `us(altgr-intl)`. Could it even be a thing from your GUI? Anyway I am a bit stunned, because the AltGr-behaviour is exactly what wikipedia defines as not a dead key:

> A dead key is different from a typical modifier key (such as AltGr or ⌥ Option) in that rather than being pressed and held while another key is struck, the dead key is pressed and released before striking the key to be modified

But your renaming is definitive a improvement for me, and if nobody else in the linux world cares about the definition of a dead key .... well I suppose then it is not the right place anyway to discuss it.
So I guess I can barely live with that... Thank you!

**Comment by enigma9o7** [comment]
@beatgutzwiller

That is what a dead key is.  A key that doesnt move the cursor forward on a
typewriter.   If you have to press alt-gr+key to get a dead key, it's still
a dead key if it behaves exactly as a dead like according to your
definition.   A dead key is not a modifier.  Alt-gr is a modifier.  For
example, right-alt+' on my keyboard is a dead key, as I use us-intl with
altgr-dead keys.

**Comment by beatgutzwiller** [comment]
@enigma9o7 
This is correct. However Deadkeys are moved to the 3rd Layer with the AltGr Variant.
There are still available but don't have to be used for most cases. I for example can type German without ever needing a single dead key, because äöü etc are directly accessible via alt-gr. 
But thank you for the comment. I believe the name makes sense in this thinking because you could argue that the dead keys are hidden behind the AltGr => "AltGr Deadkeys".

In the end it is still strange to name a layout-variant after the one functionality it tries to reduce to a bear minimum!

@anssih Since we are merely discussing about semantics now, you can close the issue as soon as you like.

**Comment by anssih** [comment]
@beatgutzwiller 

> What the heck....??! I mean I totally believe you (Do not really have that kind of guy, mine says `us(altgr-intl)`. Could it even be a thing from your GUI?

You can see the name "English (intl., with AltGr dead keys)" in the layout definition here:
https://cgit.freedesktop.org/xkeyboard-config/tree/symbols/us#n804

> Anyway I am a bit stunned, because the AltGr-behaviour is exactly what wikipedia defines as not a dead key:
> 
> > A dead key is different from a typical modifier key (such as AltGr or ⌥ Option) in that rather than being pressed and held while another key is struck, the dead key is pressed and released before striking the key to be modified

That same [article](https://en.wikipedia.org/wiki/Dead_key) also says

> In the absence of a default dead key, even a normal printing key can temporarily be altered to function as a dead key by simultaneously holding down another modifier key (typically AltGr or Option).

which is what we have here.

**Comment by anssih** [comment]
@pierre-muth 

> I'm used to get an apostrophe ( ' ) if I combine this key with a space, and not the accent alone ( ´ ). Same with the shifted key plus space, I'm used to get a the quotation marks ( " ) and not a umlaut alone ( ¨ ). As well, with this key plus the [ c ], I'm used to get a ( ç ) and not a ( ć ). To get the ç, it is [atl]+[c] which is rather hard (have small fingers ;) ).

Ah, that's interesting. Unfortunately I don't think there is any way to customize the output of the combining characters via Android keyboard layouts.

For ç, we could put it also on e.g. Fn+G if that would help?

Out of interest, is the behavior you describe above on Windows or also on Linux?

**Comment by beatgutzwiller** [comment]
@anssih Sorry I may have been unclear, I have absolutely no doubt that you are right and the layout may be called like this. I am just stunned that it is! 
I absolutely agree that you should call the layout like this, if this is the way it normally is named. I am just not used to it (AwesomeWM just reads out the xkb values and displays `us(altgr-intl)`).
The change you did is at least a big improvement for me!

**Comment by pierre-muth** [comment]
> @pierre-muth
> 
> > I'm used to get an apostrophe ( ' ) if I combine this key with a space, and not the accent alone ( ´ ). Same with the shifted key plus space, I'm used to get a the quotation marks ( " ) and not a umlaut alone ( ¨ ). As well, with this key plus the [ c ], I'm used to get a ( ç ) and not a ( ć ). To get the ç, it is [atl]+[c] which is rather hard (have small fingers ;) ).
> 
> Ah, that's interesting. Unfortunately I don't think there is any way to customize the output of the combining characters via Android keyboard layouts.
> Out of interest, is the behavior you describe above on Windows or also on Linux?
 
Hi @anssih ,
You're right, the "ç" is on Windows, on Ubuntu I get the "ć". However the [" '] plus [ space ] give " or ' on both platform. Anyway, as you said, it is on the android side.

> For ç, we could put it also on e.g. Fn+G if that would help?

If you think it is an acceptable customization over the official layout, I would say yes, I can reach [Fn] and G with both thumbs ^^

Thanks a lot !
