### ISSUE TITLE
Wish: Sticky modifier keys (pro1)

### ISSUE THREAD

**Issue by Spoil001** [anssih/finqwerty#6]
A layout that has sticky shift / alt / yellow modifier keys would be great.

I'm not sure if it's even possible, but it would make my live a little bit easier.

**Comment by Derecho** [comment]
I'd love to have this as well, and I recall having this on some of my previous phones like the Photon Q and Desire Z.

I've searched around a bit and it appears that this behaviour may be present for keyboard layouts that define their type as ALPHA. The layouts in this project have the type OVERLAY, which I don't actually see back in the documentation ( https://source.android.com/devices/input/key-character-map-files ),

**Comment by Spoil001** [comment]
Alpha might also get predictions showing up with gboard.

**Comment by anssih** [comment]
Yes, sticky modifiers work with ALPHA, unfortunately apps (like FinQwerty) can only contain layouts with type OVERLAY, which just preserves the stock type. On stock Pro1 firmware the type is incorrectly set to FULL which means a full PC keyboard with no predicitions and stickiness.

If somebody comes up with a soluation, I can add it, but currently I do not see any way to implement this in FinQwerty.
