### ISSUE TITLE
Pro1: Sym doesn't wake phone

### ISSUE THREAD

**Issue by Spoil001** [anssih/finqwerty#8]
FinQWERTY 1.5.3 from PlayStore.
German for Physical QWERTZ.

**Comment by Spoil001** [comment]
A diff of the layouts shows that the following is missing from QWERTZ:

# orig SYM but SYM does not do anything at the moment
# so use as back/wakeup for now
map key 249 WAKEUP

# ROW 1

key ESCAPE {
    base:                               fallback BACK
    fn:                                 replace HOME
}

**Comment by Spoil001** [comment]
Is there a reason why WAKEUP is not on every key e.g. as fallback?

**Comment by anssih** [comment]
> Is there a reason why WAKEUP is not on every key e.g. as fallback?

Someone tested that "fallback WAKEUP" did not work. I haven't had the time to check it myself yet as I just got the device.

The list of wakeup keys is hardcoded in Android `frameworks/base/core/java/android/view/KeyEvent.java`, function `isWakeKey()`. The best option would be to have e.g. KEYCODE_ESCAPE (and maybe other keys) added there.

**Comment by anssih** [comment]
Fixed in v1.5.4, thanks.
